services:
  backend:
    build: ./backend
    # depends_on:
    #   - db
    ports:
      - "5000:5000"
    networks:
      - webnet
  
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - webnet

volumes:
  db_data:

networks:
  webnet:
    driver: bridge